---
controller_credentials:
- name: Etherpad MariaDB Credentials - etherpad_apb
  description: MariaDB database credentials for the Etherpad APB deployment, including
    root password, application user, and application password
  organization: Default
  credential_type: Etherpad MariaDB Credentials
  update_secrets: true
  inputs:
    mariadb_name: '{{ mariadb_name }}'
    mariadb_user: '{{ mariadb_user }}'
    mariadb_password: '{{ vault_mariadb_password }}'
    mariadb_root_password: '{{ vault_mariadb_root_password }}'
- name: Etherpad Admin Credentials - etherpad_apb
  description: Etherpad Lite admin user credentials injected into the Etherpad DeploymentConfig
  organization: Default
  credential_type: Etherpad Admin Credentials
  update_secrets: true
  inputs:
    etherpad_admin_user: '{{ etherpad_admin_user }}'
    etherpad_admin_password: '{{ vault_etherpad_admin_password }}'
