---
galaxy_info:
  author: Migration Tool
  description: Deploy Etherpad Lite and MariaDB to OpenShift/Kubernetes using kubernetes.core
  galaxy_tags: []
  license: Apache-2.0
  min_ansible_version: "2.10"
  namespace: x2a
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: EL
      versions:
        - "8"
        - "9"
  role_name: etherpad_apb
dependencies: []
